CREATE TABLE "COMMS"."VODAFONE_FEE" (
	"ISSUE_DATE" DATE,
	"CALLER_ID" NUMBER(38,0),
	"BILL_ID" VARCHAR2(16 BYTE),
	"CONTRACT_TYPE" VARCHAR2(64 BYTE),
	"DISCOUNT_FEE" NUMBER(38,2),
	"MONTHLY_FEE" NUMBER(38,2),
	"CALL_CHARGE" NUMBER(38,2),
	"DISCOUNT_CHARGE" NUMBER(38,2),
	"DISCOUNT_MISC" NUMBER(38,2),
	"MOBILE_TAX" NUMBER(38,2),
	"VATED_AMOUNT" NUMBER(38,2),
	"UNTAXED_AMOUNT" NUMBER(38,2),
	"TOTAL_AMOUNT" NUMBER(38,2),
	"VAT_AMOUNT" NUMBER(38,2),
	"CALL_COUNT" NUMBER(38,0),
	"CALL_DURATION" VARCHAR2(20 BYTE),
	"TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp
	"CALL_VOLUME" NUMBER(38,2),
);
COMMENT ON COLUMN "COMMS"."VODAFONE_FEE"."ISSUE_DATE" IS 'Ημερομηνία Έκδοσης';
COMMENT ON COLUMN "COMMS"."VODAFONE_FEE"."CALLER_ID" IS 'Αριθμός Κινητού';
COMMENT ON COLUMN "COMMS"."VODAFONE_FEE"."BILL_ID" IS 'Αριθμός λογαριασμού';
COMMENT ON COLUMN "COMMS"."VODAFONE_FEE"."CONTRACT_TYPE" IS 'Πρόγραμμα σύνδεσης';
COMMENT ON COLUMN "COMMS"."VODAFONE_FEE"."MONTHLY_FEE" IS 'Πάγια τέλη';
COMMENT ON COLUMN "COMMS"."VODAFONE_FEE"."DISCOUNT_FEE" IS 'Εκπτώσεις παγίων';
COMMENT ON COLUMN "COMMS"."VODAFONE_FEE"."CALL_CHARGE" IS 'Χρεώσεις επικοινωνίας';
COMMENT ON COLUMN "COMMS"."VODAFONE_FEE"."DISCOUNT_CHARGE" IS 'Έκπτωση xρεώσεων επικοινωνίας';
COMMENT ON COLUMN "COMMS"."VODAFONE_FEE"."DISCOUNT_MISC" IS 'Αλλες Εκπτώσεις Χρεώσεις';
COMMENT ON COLUMN "COMMS"."VODAFONE_FEE"."MOBILE_TAX" IS 'Φόρος κινητής τηλεφωνίας';
COMMENT ON COLUMN "COMMS"."VODAFONE_FEE"."UNTAXED_AMOUNT" IS 'Ποσό που δεν υπόκειται σε φόρο Κιν Τηλ';
COMMENT ON COLUMN "COMMS"."VODAFONE_FEE"."VATED_AMOUNT" IS 'Ποσό που υπόκειται σε ΦΠΑ';
COMMENT ON COLUMN "COMMS"."VODAFONE_FEE"."VAT_AMOUNT" IS 'ΦΠΑ';
COMMENT ON COLUMN "COMMS"."VODAFONE_FEE"."TOTAL_AMOUNT" IS 'Συνολικό ποσό';
COMMENT ON COLUMN "COMMS"."VODAFONE_FEE"."CALL_COUNT" IS 'Συνολικός αριθμός κλήσεων';
COMMENT ON COLUMN "COMMS"."VODAFONE_FEE"."CALL_DURATION" IS 'Χρονική διάρκεια επικοινωνίας';
COMMENT ON COLUMN "COMMS"."VODAFONE_FEE"."CALL_VOLUME" IS 'Όγκος δεδομένων';
COMMENT ON COLUMN "COMMS"."VODAFONE_FEE"."TIMESTAMP" IS 'Creation Date';

CREATE UNIQUE INDEX "COMMS"."VODAFONE_FEE_PK" ON "COMMS"."VODAFONE_FEE" ("ISSUE_DATE", "CALLER_ID");
CREATE UNIQUE INDEX "COMMS"."VODAFONE_FEE_UK_BILL" ON "COMMS"."VODAFONE_FEE" ("CALLER_ID", "BILL_ID");

ALTER TABLE "COMMS"."VODAFONE_FEE" MODIFY ("ISSUE_DATE" NOT NULL ENABLE);
ALTER TABLE "COMMS"."VODAFONE_FEE" MODIFY ("CALLER_ID" NOT NULL ENABLE);
ALTER TABLE "COMMS"."VODAFONE_FEE" MODIFY ("BILL_ID" NOT NULL ENABLE);
ALTER TABLE "COMMS"."VODAFONE_FEE" MODIFY ("CONTRACT_TYPE" NOT NULL ENABLE);
ALTER TABLE "COMMS"."VODAFONE_FEE" MODIFY ("MONTHLY_FEE" NOT NULL ENABLE);
ALTER TABLE "COMMS"."VODAFONE_FEE" MODIFY ("DISCOUNT_FEE" NOT NULL ENABLE);
ALTER TABLE "COMMS"."VODAFONE_FEE" MODIFY ("CALL_CHARGE" NOT NULL ENABLE);
ALTER TABLE "COMMS"."VODAFONE_FEE" MODIFY ("DISCOUNT_CHARGE" NOT NULL ENABLE);
ALTER TABLE "COMMS"."VODAFONE_FEE" MODIFY ("DISCOUNT_MISC" NOT NULL ENABLE);
ALTER TABLE "COMMS"."VODAFONE_FEE" MODIFY ("MOBILE_TAX" NOT NULL ENABLE);
ALTER TABLE "COMMS"."VODAFONE_FEE" MODIFY ("UNTAXED_AMOUNT" NOT NULL ENABLE);
ALTER TABLE "COMMS"."VODAFONE_FEE" MODIFY ("VATED_AMOUNT" NOT NULL ENABLE);
ALTER TABLE "COMMS"."VODAFONE_FEE" MODIFY ("VAT_AMOUNT" NOT NULL ENABLE);
ALTER TABLE "COMMS"."VODAFONE_FEE" MODIFY ("TOTAL_AMOUNT" NOT NULL ENABLE);
ALTER TABLE "COMMS"."VODAFONE_FEE" MODIFY ("CALL_COUNT" NOT NULL ENABLE);
ALTER TABLE "COMMS"."VODAFONE_FEE" MODIFY ("CALL_DURATION" NOT NULL ENABLE);
ALTER TABLE "COMMS"."VODAFONE_FEE" MODIFY ("CALL_VOLUME" NOT NULL ENABLE);
ALTER TABLE "COMMS"."VODAFONE_FEE" MODIFY ("TIMESTAMP" NOT NULL ENABLE);

ALTER TABLE "COMMS"."VODAFONE_FEE" ADD CONSTRAINT "VODAFONE_FEE_PK" PRIMARY KEY ("ISSUE_DATE", "CALLER_ID");
ALTER TABLE "COMMS"."VODAFONE_FEE" ADD CONSTRAINT "VODAFONE_FEE_UK_BILL" UNIQUE ("CALLER_ID", "BILL_ID");

===============================================================================

CREATE TABLE "COMMS"."COMM_IMP_VODAFONE" (
	"CALLER_ID" NUMBER(*,0),
	"CALL_DATE" DATE,
	"CALL_TYPE" VARCHAR2(32 BYTE),
	"ROAMING_INFO" VARCHAR2(64 BYTE),
	"CALLED_APN" VARCHAR2(32 BYTE),
	"CALLED_NET" VARCHAR2(16 BYTE),
	"CALL_DURATION" NUMBER(*,0),
	"CALL_VOLUME" NUMBER(*,3),
	"CALL_CHARGE" NUMBER(*,2),
	"BILL_ID" VARCHAR2(16 BYTE) DEFAULT 0000000000,
	"PROVIDER" VARCHAR2(128 BYTE),
	"PAID_DURATION" VARCHAR2(20 BYTE)
);
COMMENT ON COLUMN "COMMS"."COMM_IMP_VODAFONE"."PAID_DURATION" IS 'will always be empty, as the original values is inserted in call_duration.';
ALTER TABLE "COMMS"."COMM_IMP_VODAFONE" MODIFY ("CALLER_ID" NOT NULL ENABLE);
ALTER TABLE "COMMS"."COMM_IMP_VODAFONE" MODIFY ("CALL_CHARGE" NOT NULL ENABLE);
ALTER TABLE "COMMS"."COMM_IMP_VODAFONE" MODIFY ("BILL_ID" NOT NULL ENABLE);

===============================================================================

CREATE TABLE "COMMS"."VODAFONE_LOG" (
	"CALLER_ID" NUMBER(*,0),
	"CALL_DATE" DATE,
	"CALL_TYPE" VARCHAR2(42 BYTE),
	"ROAMING_INFO" VARCHAR2(64 BYTE),
	"CALLED_APN" VARCHAR2(42 BYTE),
	"CALLED_NET" VARCHAR2(16 BYTE),
	"CALL_DURATION" NUMBER(*,0),
	"CALL_VOLUME" NUMBER(*,2),
	"CALL_CHARGE" NUMBER(*,2),
	"TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp,
	"BILL_ID" VARCHAR2(16 BYTE) DEFAULT 0000000000
);

COMMENT ON COLUMN "COMMS"."VODAFONE_LOG"."BILL_ID" IS 'link between vodafone_fee and _log';

ALTER TABLE "COMMS"."VODAFONE_LOG" MODIFY ("CALLER_ID" NOT NULL ENABLE);
ALTER TABLE "COMMS"."VODAFONE_LOG" MODIFY ("CALL_CHARGE" NOT NULL ENABLE);
ALTER TABLE "COMMS"."VODAFONE_LOG" MODIFY ("TIMESTAMP" NOT NULL ENABLE);
ALTER TABLE "COMMS"."VODAFONE_LOG" MODIFY ("BILL_ID" NOT NULL ENABLE);

===============================================================================

CREATE TABLE "COMMS"."COMM_CHARGES" (
	"VESSELCODE" VARCHAR2(4 BYTE),
	"PROVIDER" NUMBER(*,0),
	"RECEIVED" DATE DEFAULT sysdate,
	"REFERENCE" VARCHAR2(64 BYTE),
	"INVOICE" VARCHAR2(64 BYTE),
	"PERIOD" VARCHAR2(64 BYTE),
	"DATE_FROM" DATE,
	"DATE_TO" DATE,
	"TRAFFIC_TYPE" NUMBER(*,0) DEFAULT 0,
	"TRAFFIC" NUMBER DEFAULT 0,
	"IN_BUNDLE" NUMBER(*,0) DEFAULT 0,
	"AMOUNT" NUMBER DEFAULT 0,
	"CURRENCY" VARCHAR2(3 BYTE) DEFAULT 'USD',
	"COMMENTS" VARCHAR2(128 BYTE),
	"TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp
);

CREATE UNIQUE INDEX "COMMS"."COMM_CHARGES_PK" ON "COMMS"."COMM_CHARGES" ("VESSELCODE", "PROVIDER", "REFERENCE", "PERIOD", "DATE_FROM", "DATE_TO", "TRAFFIC_TYPE", "TRAFFIC", "AMOUNT", "CURRENCY");

ALTER TABLE "COMMS"."COMM_CHARGES" ADD CONSTRAINT "COMM_CHARGES_PK" PRIMARY KEY ("VESSELCODE", "PROVIDER", "REFERENCE", "PERIOD", "DATE_FROM", "DATE_TO", "TRAFFIC_TYPE", "TRAFFIC", "AMOUNT", "CURRENCY");
ALTER TABLE "COMMS"."COMM_CHARGES" MODIFY ("VESSELCODE" NOT NULL ENABLE);
ALTER TABLE "COMMS"."COMM_CHARGES" MODIFY ("PROVIDER" NOT NULL ENABLE);
ALTER TABLE "COMMS"."COMM_CHARGES" MODIFY ("RECEIVED" NOT NULL ENABLE);
ALTER TABLE "COMMS"."COMM_CHARGES" MODIFY ("REFERENCE" NOT NULL ENABLE);
ALTER TABLE "COMMS"."COMM_CHARGES" MODIFY ("PERIOD" NOT NULL ENABLE);
ALTER TABLE "COMMS"."COMM_CHARGES" MODIFY ("DATE_FROM" NOT NULL ENABLE);
ALTER TABLE "COMMS"."COMM_CHARGES" MODIFY ("DATE_TO" NOT NULL ENABLE);
ALTER TABLE "COMMS"."COMM_CHARGES" MODIFY ("TRAFFIC_TYPE" NOT NULL ENABLE);
ALTER TABLE "COMMS"."COMM_CHARGES" MODIFY ("TRAFFIC" NOT NULL ENABLE);
ALTER TABLE "COMMS"."COMM_CHARGES" MODIFY ("IN_BUNDLE" NOT NULL ENABLE);
ALTER TABLE "COMMS"."COMM_CHARGES" MODIFY ("AMOUNT" NOT NULL ENABLE);
ALTER TABLE "COMMS"."COMM_CHARGES" MODIFY ("CURRENCY" NOT NULL ENABLE);
ALTER TABLE "COMMS"."COMM_CHARGES" MODIFY ("TIMESTAMP" NOT NULL ENABLE);
